@NationsApi_HostAddress = http://localhost:5196

GET {{NationsApi_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{NationsApi_HostAddress}}/weatherforecast/
Accept: application/json

###
